<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Storage;

class MujiStorageSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
    [
        'name' => '収納キャリーボックス・ワイド',
        'width' => 15,
        'height' => 8,
        'depth' => 32,
        'image' => 'images/carrybox.wide.png',
        'price' => 1090,
    ],
    [
        'name' => 'デスク内整理トレー１',
        'width' => 10,
        'height' => 4,
        'depth' => 10,
        'image' => 'images/desktore-1.png',
        'price' => 150,
    ],
    [
        'name' => 'デスク内整理トレー2',
        'width' => 10,
        'height' => 4,
        'depth' => 20,
        'image' => 'images/desktore-2.png',
        'price' => 250,
    ],
    [
        'name' => 'デスク内整理トレー3',
        'width' => 7,
        'height' => 4,
        'depth' => 20,
        'image' => 'images/desktore-3.png',
        'price' => 190,
    ],
    [
        'name' => 'デスク内整理トレー4',
        'width' => 14,
        'height' => 4,
        'depth' => 20,
        'image' => 'images/desktore-4.png',
        'price' => 250,
    ],
    [
        'name' => 'スタンドファイルボックス',
        'width' => 10,
        'height' => 32,
        'depth' => 28,
        'image' => 'images/filebox.stand.png',
        'price' => 590,
    ],
    [
        'name' => 'スタンドファイルボックス・ワイド',
        'width' => 15,
        'height' => 32,
        'depth' => 28,
        'image' => 'images/filebox.stand.wide.png',
        'price' => 790,
    ],
    [
        'name' => 'ファイルボックス・スタンダード1/2',
        'width' => 10,
        'height' => 12,
        'depth' => 32,
        'image' => 'images/filebox.standard.half.png',
        'price' => 390,
    ],
    [
        'name' => 'ファイルボックス・スタンダードタイプ',
        'width' => 10,
        'height' => 24,
        'depth' => 32,
        'image' => 'images/filebox.standard.png',
        'price' => 590,
    ],
    [
        'name' => 'ファイルボックス・スタンダード・ワイド1/2',
        'width' => 15,
        'height' => 12,
        'depth' => 32,
        'image' => 'images/filebox.standard.wide.half.png',
        'price' => 590,
    ],
    [
        'name' => 'ファイルボックス・スタンダード・ワイド',
        'width' => 15,
        'height' => 24,
        'depth' => 32,
        'image' => 'images/filebox.standard.wide.png',
        'price' => 790,
    ],
    [
        'name' => '小物収納ボックス３段',
        'width' => 11,
        'height' => 32,
        'depth' => 25,
        'image' => 'images/komonosyuunoubox3.png',
        'price' => 2290,
    ],
    [
        'name' => '小物収納ボックス6段',
        'width' => 11,
        'height' => 32,
        'depth' => 25,
        'image' => 'images/komonosyuunoubox6.png',
        'price' => 2990,
    ],
    [
        'name' => 'やわらかポリエチレンケース・深',
        'width' => 26,
        'height' => 32,
        'depth' => 36,
        'image' => 'images/porietiren.deep.png',
        'price' => 1090,
    ],
    [
        'name' => 'やわらかポリエチレンケース・ハーフ・大',
        'width' => 18,
        'height' => 24,
        'depth' => 26,
        'image' => 'images/porietiren.half.large.png',
        'price' => 690,
    ],
    [
        'name' => 'やわらかポリエチレンケース・ハーフ・中',
        'width' => 18,
        'height' => 16,
        'depth' => 26,
        'image' => 'images/porietiren.half.medium.png',
        'price' => 590,
    ],
    [
        'name' => 'やわらかポリエチレンケース・ハーフ・小',
        'width' => 18,
        'height' => 8,
        'depth' => 26,
        'image' => 'images/porietiren.half.small.png',
        'price' => 490,
    ],
    [
        'name' => 'やわらかポリエチレンケース・大',
        'width' => 26,
        'height' => 24,
        'depth' => 36,
        'image' => 'images/porietiren.large.png',
        'price' => 890,
    ],
    [
        'name' => 'やわらかポリエチレンケース・小',
        'width' => 26,
        'height' => 8,
        'depth' => 36,
        'image' => 'images/porietiren.small.png',
        'price' => 590,
    ],
    [
        'name' => 'やわらかポリエチレンケース・中',
        'width' => 26,
        'height' => 16,
        'depth' => 36,
        'image' => 'images/porietiren.medium.png',
        'price' => 690,
    ],
    [
        'name' => 'ラタン長方形ボックス・小',
        'width' => 26,
        'height' => 12,
        'depth' => 18,
        'image' => 'images/ratan.box.small.png',
        'price' => 1890,
    ],
       [
        'name' => 'ラタン長方形ボックス・フタ付',
        'width' => 26,
        'height' => 16,
        'depth' => 18,
        'image' => 'images/ratan.hutatuki.png',
        'price' => 1990,
    ],
    [
        'name' => 'ラタン角型バスケット・大',
        'width' => 35,
        'height' => 24,
        'depth' => 36,
        'image' => 'images/ratan.kaku.large.png',
        'price' => 3990,
    ],
    [
        'name' => 'ラタン角型バスケット・中',
        'width' => 35,
        'height' => 16,
        'depth' => 36,
        'image' => 'images/ratan.kaku.medium.png',
        'price' => 2990,
    ],
    [
        'name' => 'ラタン長方形バスケット・大',
        'width' => 36,
        'height' => 24,
        'depth' => 26,
        'image' => 'images/ratan.large.png',
        'price' => 2990,
    ],
    [
        'name' => 'ラタン長方形バスケット・特大',
        'width' => 36,
        'height' => 31,
        'depth' => 26,
        'image' => 'images/ratan.largelarge.png',
        'price' => 3990,
    ],
    [
        'name' => 'ラタン長方形バスケット・中',
        'width' => 36,
        'height' => 16,
        'depth' => 26,
        'image' => 'images/ratan.medium.png',
        'price' => 2990,
    ],
    [
        'name' => 'ラタン長方形バスケット・小',
        'width' => 36,
        'height' => 12,
        'depth' => 26,
        'image' => 'images/ratan.small.png',
        'price' => 1990,
    ],
    [
        'name' => 'ポリプロピレン整理ボックス１',
        'width' => 9,
        'height' => 5,
        'depth' => 9,
        'image' => 'images/seiribox1.png',
        'price' => 100,
    ],
    [
        'name' => 'ポリプロピレン整理ボックス２',
        'width' => 9,
        'height' => 5,
        'depth' => 26,
        'image' => 'images/seiribox2.png',
        'price' => 190,
    ],
    [
        'name' => 'ポリプロピレン整理ボックス３',
        'width' => 17,
        'height' => 5,
        'depth' => 26,
        'image' => 'images/seiribox3.png',
        'price' => 250,
    ],
    [
        'name' => 'ポリプロピレン整理ボックス４',
        'width' => 12,
        'height' => 5,
        'depth' => 34,
        'image' => 'images/seiribox4.png',
        'price' => 220,
    ],
    [
        'name' => 'ソフトボックス浅型ハーフ',
        'width' => 13,
        'height' => 12,
        'depth' => 37,
        'image' => 'images/softbox.half.asa.small.png',
        'price' => 490,
    ],
    [
        'name' => 'ソフトボックス角型・小・フタ式',
        'width' => 35,
        'height' => 16,
        'depth' => 35,
        'image' => 'images/softbox.half.medium.hutatuki.png',
        'price' => 990,
    ],
    [
        'name' => 'ソフトボックス角型・小',
        'width' => 35,
        'height' => 16,
        'depth' => 35,
        'image' => 'images/softbox.kaku.small.png',
        'price' => 890,
    ],
    [
        'name' => 'ソフトボックス長方形・大',
        'width' => 37,
        'height' => 34,
        'depth' => 26,
        'image' => 'images/softbox.large.png',
        'price' => 990,
    ],
    [
        'name' => 'ソフトボックス長方形・中',
        'width' => 37,
        'height' => 26,
        'depth' => 26,
        'image' => 'images/softbox.medium.png',
        'price' => 890,
    ],
    [
        'name' => 'ソフトボックス長方形・小',
        'width' => 37,
        'height' => 16,
        'depth' => 26,
        'image' => 'images/softbox.small.png',
        'price' => 690,
    ],
    [
        'name' => 'ステンレスワイヤーバスケット１',
        'width' => 26,
        'height' => 18,
        'depth' => 18,
        'image' => 'images/stenressbasket1.png',
        'price' => 1290,
    ],
    [
        'name' => 'ステンレスワイヤーバスケット２',
        'width' => 37,
        'height' => 8,
        'depth' => 26,
        'image' => 'images/stenressbasket2.png',
        'price' => 1490,
    ],
    [
        'name' => 'ステンレスワイヤーバスケット３',
        'width' => 37,
        'height' => 12,
        'depth' => 26,
        'image' => 'images/stenressbasket3.png',
        'price' => 1790,
    ],
    [
        'name' => 'ステンレスワイヤーバスケット４',
        'width' => 37,
        'height' => 18,
        'depth' => 26,
        'image' => 'images/stenressbasket4.png',
        'price' => 1990,
    ],
    [
        'name' => 'ステンレスワイヤーバスケット５',
        'width' => 37,
        'height' => 24,
        'depth' => 26,
        'image' => 'images/stenressbasket5.png',
        'price' => 2490,
    ],
    [
        'name' => 'ステンレスワイヤーバスケット6',
        'width' => 51,
        'height' => 18,
        'depth' => 37,
        'image' => 'images/stenressbasket6.png',
        'price' => 2990,
    ],
    [
        'name' => 'ステンレスワイヤーバスケット７',
        'width' => 51,
        'height' => 24,
        'depth' => 37,
        'image' => 'images/stenressbasket7.png',
        'price' => 3990,
    ],
    [
        'name' => 'トタンボックス・大・高さ8.5cmタイプ',
        'width' => 26,
        'height' => 9,
        'depth' => 34,
        'image' => 'images/totan8.5.large.png',
        'price' => 990,
    ],
    [
        'name' => 'トタンボックス・小・高さ8.5cmタイプ',
        'width' => 19,
        'height' => 9,
        'depth' => 27,
        'image' => 'images/totan8.5.small.png',
        'price' => 790,
    ],
    [
        'name' => 'トタンボックス・大・高さ16cmタイプ',
        'width' => 26,
        'height' => 16,
        'depth' => 37,
        'image' => 'images/totan16.large.png',
        'price' => 1190,
    ],
    [
        'name' => 'トタンボックス・小・高さ16cmタイプ',
        'width' => 19,
        'height' => 16,
        'depth' => 29,
        'image' => 'images/totan16.small.png',
        'price' => 1090,
    ],
    [
        'name' => 'トタンボックス・大・高さ24cmタイプ',
        'width' => 26,
        'height' => 24,
        'depth' => 37,
        'image' => 'images/totan24.large.png',
        'price' => 1590,
    ],
];


        foreach ($items as $item) {
            Storage::create([
                'user_id' => null,
                'name' => $item['name'],
                'width' => $item['width'],
                'height' => $item['height'],
                'depth' => $item['depth'],
                'image' => $item['image'],
                'price' => $item['price'],
            ]);

        }
    }
}
