services:
  - type: web
    name: pittarikun
    env: docker
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: APP_NAME
        value: Pittarikun
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        generateValue: true
      - key: LOG_CHANNEL
        value: stderr
      - key: LOG_LEVEL
        value: info
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: pittarikun-db
          property: connectionString
      - key: SESSION_DRIVER
        value: database
      - key: CACHE_STORE
        value: database
      - key: QUEUE_CONNECTION
        value: database
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: STRIPE_SECRET
        sync: false
      - key: GITHUB_TOKEN
        sync: false
      - key: STRIPE_ALLOW_ANY_CARD
        value: "false"

databases:
  - name: pittarikun-db
    databaseName: pittarikun
    user: pittarikun
